name: 'Netlify Deploy'

on:
    pull_request:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: production
        env:
            PORT: $PORT
            TIMEZONE: $TIMEZONE
            DS_HOST: ${{ secrets.DS_HOST }}
            DS_TYPE: ${{ secrets.DS_TYPE }}
            DS_USERNAME: ${{ secrets.DS_USERNAME }}
            DS_PASSWORD: ${{ secrets.DS_PASSWORD }}
            DS_DATABASE: ${{ secrets.DS_DATABASE }}
        steps:
            - name: Repository Checkout
              uses: actions/checkout@v4 # clona toda a branch e joga na máquina q vai rodar a pipe.

            # Acessando variáveis do ambiente do GitHub Actions
            - name: Use Environment Variables
              run: |
                  echo "Secret: ${{ secrets.DS_TYPE }}"
                  echo "Variable: $PORT"

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Run install, build and start
              run: |
                  npm install
                  npm run build
                  node dist/server.js
            # - name: Deploy Heroku
            #   uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
            #   with:
            #       heroku_api_key: ${{secrets.HEROKU_TOKEN}}
            #       heroku_app_name: 'therapyeasy' #Must be unique in Heroku
            #       heroku_email: 'joaopfsiqueiraa@gmail.com'
